# Generated by Django 3.2 on 2023-03-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230321_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='Код потверждения'),
        ),
    ]
