# Generated by Django 3.2 on 2023-03-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Обязательное поле.', max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
