# Generated by Django 3.2 on 2023-03-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Обязательное поле.', max_length=254, unique=True, verbose_name='email'),
        ),
    ]
